import type { IncidentRecord } from "./types.js";

/**
 * Pure postmortem drafting (#112, ADR-0112 §8). When an incident resolves, the loop renders a
 * timeline + 5-whys-skeleton markdown that an agent (or a human) refines. The engine writes the
 * returned markdown under `docs/postmortems/` via the `PostmortemWriter` seam and records the path on
 * the incident row; the Founder Console links it. Pure + deterministic so it is fully unit-tested.
 */

export interface PostmortemTimelineEntry {
  /** ISO timestamp of the event. */
  at: string;
  event: string;
}

/** Sanitize a service name into a path-safe slug (no slashes, lowercase, dashed). */
function slug(s: string): string {
  return s
    .toLowerCase()
    .replace(/[^a-z0-9_]+/g, "-")
    .replace(/^-+|-+$/g, "");
}

/** The stable repo-relative path a drafted postmortem is written to. */
export function postmortemPath(incident: IncidentRecord, dateStr: string): string {
  return `docs/postmortems/${dateStr}-${slug(incident.service)}-${incident.sloKind}-${incident.id.slice(0, 8)}.md`;
}

/** Render the postmortem draft markdown for a resolved incident. */
export function draftPostmortem(
  incident: IncidentRecord,
  timeline: PostmortemTimelineEntry[],
): string {
  const duration =
    incident.resolvedAt && incident.openedAt
      ? `${Math.max(0, Math.round((incident.resolvedAt.getTime() - incident.openedAt.getTime()) / 1000))}s`
      : "(unresolved)";

  const timelineRows = timeline.length
    ? timeline.map((t) => `- \`${t.at}\` — ${t.event}`).join("\n")
    : "- (no timeline recorded)";

  return [
    `# Postmortem: ${incident.service} ${incident.sloKind} breach (${incident.id.slice(0, 8)})`,
    ``,
    `> **Draft** auto-generated by the SRE Loop (#112). An agent/human refines the 5-whys + action items.`,
    ``,
    `- **Service:** ${incident.service}`,
    `- **SLO breached:** ${incident.sloKind} — observed ${incident.observedValue}, target ${incident.targetValue}`,
    `- **Severity:** ${incident.severity}`,
    `- **Opened:** ${incident.openedAt.toISOString()}`,
    `- **Resolved:** ${incident.resolvedAt ? incident.resolvedAt.toISOString() : "(open)"}`,
    `- **Duration:** ${duration}`,
    ``,
    `## Summary`,
    ``,
    `The \`${incident.service}\` service breached its \`${incident.sloKind}\` SLO. The SRE Loop opened`,
    `incident \`${incident.id}\`, launched a triage agent with a failure bundle, and resolved the`,
    `incident when the SLO recovered.`,
    ``,
    `## Timeline`,
    ``,
    timelineRows,
    ``,
    `## 5 Whys`,
    ``,
    `1. **Why did the SLO breach?** _(fill in — start from the recent deploys in the failure bundle)_`,
    `2. **Why #2?** _(fill in)_`,
    `3. **Why #3?** _(fill in)_`,
    `4. **Why #4?** _(fill in)_`,
    `5. **Why #5 (root cause)?** _(fill in)_`,
    ``,
    `## Action items`,
    ``,
    `- [ ] _(detection)_ Did the alert fire at the right threshold? Tune the SLO target if not.`,
    `- [ ] _(remediation)_ Capture the fix (and whether it needed a #13 approval).`,
    `- [ ] _(prevention)_ What stops this recurring?`,
  ].join("\n");
}
