/**
 * Performance & capacity suite (#113, ADR-0113). Boots the real server in-process, hammers the hot
 * paths with the dependency-free closed-loop driver, enforces the perf budgets, and (re)writes the
 * measured capacity model to `docs/capacity.md`. Run it —
 *
 *   pnpm -C platform --filter @reload/server perf
 *
 * It needs a real Postgres+Redis (same as the integration suite) because it signs up a session for the
 * authenticated scenario. No agent process is spawned and no money is spent — the scenarios are
 * read/CPU paths only (see src/perf/scenarios.ts). Exits non-zero on a budget breach so the CI `perf`
 * job fails the PR on a regression. Tunables: `PERF_REQUESTS` (default 3000), `PERF_CONCURRENCY` (50).
 */
import os from "node:os";
import { writeFile } from "node:fs/promises";
import { randomUUID } from "node:crypto";
import { buildApp } from "../src/app.js";
import { closeDb } from "../src/db/index.js";
import { closeRedis } from "../src/redis/index.js";
import { runLoad } from "../src/perf/driver.js";
import { evaluateBudgets, rpsPerVcpu, type PerfResult } from "../src/perf/budgets.js";
import { buildScenarios, HOT_PATH_BUDGETS } from "../src/perf/scenarios.js";

const TOTAL = Number(process.env.PERF_REQUESTS ?? 3000);
const CONCURRENCY = Number(process.env.PERF_CONCURRENCY ?? 50);

/** Pull the `rid` session cookie out of a signup response. */
function ridCookie(res: Response): string {
  const setCookies =
    typeof res.headers.getSetCookie === "function"
      ? res.headers.getSetCookie()
      : [res.headers.get("set-cookie") ?? ""];
  for (const c of setCookies) {
    const m = /(?:^|;\s*)rid=([^;]+)/.exec(c);
    if (m) return m[1]!;
  }
  throw new Error("signup did not set an rid cookie — is Postgres reachable?");
}

function fmt(n: number, digits = 1): string {
  return n.toFixed(digits);
}

function capacityMarkdown(results: PerfResult[], vcpus: number): string {
  const stamp = new Date().toISOString();
  const lines: string[] = [];
  lines.push("# Capacity model (measured)");
  lines.push("");
  lines.push(
    "> **Generated by `pnpm -C platform --filter @reload/server perf`** — do not hand-edit. Numbers are",
  );
  lines.push(
    "> from the closed-loop load driver (`src/perf/driver.ts`) against the hot paths, on the machine that",
  );
  lines.push("> ran the suite. Re-run to refresh. See [ADR-0113](adrs/0113-performance-capacity-rails.md).");
  lines.push("");
  lines.push(`- **Generated:** ${stamp}`);
  lines.push(`- **Host vCPUs:** ${vcpus}`);
  lines.push(`- **Load:** ${TOTAL} requests/scenario @ concurrency ${CONCURRENCY}`);
  lines.push("");
  lines.push("| Scenario | req/s | req/s per vCPU | p50 (ms) | p99 (ms) | errors |");
  lines.push("| --- | ---: | ---: | ---: | ---: | ---: |");
  for (const r of results) {
    lines.push(
      `| \`${r.name}\` | ${fmt(r.rps, 0)} | ${fmt(rpsPerVcpu(r.rps, vcpus), 0)} | ${fmt(r.p50Ms, 2)} | ${fmt(r.p99Ms, 2)} | ${r.errors} |`,
    );
  }
  lines.push("");
  const baseline = results.find((r) => r.name === "baseline");
  if (baseline) {
    lines.push(
      `**Per-vCPU anchor:** the framework baseline sustains **~${fmt(rpsPerVcpu(baseline.rps, vcpus), 0)} req/s per vCPU**. ` +
        "Horizontal scale-out is linear in replicas (the server is stateless — see `scaling.md`); size the " +
        "fleet by dividing expected peak req/s by this number, then add headroom for the saturation alerts.",
    );
  }
  lines.push("");
  return lines.join("\n");
}

async function main(): Promise<void> {
  process.env.STRIPE_WEBHOOK_SECRET ??= "whsec_perf_nonsecret";
  const app = buildApp();
  await app.listen({ port: 0, host: "127.0.0.1" });
  const addr = app.server.address();
  if (!addr || typeof addr === "string") throw new Error("failed to bind a port");
  const baseUrl = `http://127.0.0.1:${addr.port}`;

  // Sign up once for the authenticated scenario.
  const slug = `perf-${randomUUID()}`;
  const signup = await fetch(`${baseUrl}/auth/signup`, {
    method: "POST",
    headers: { "content-type": "application/json" },
    body: JSON.stringify({
      email: `perf-${randomUUID()}@example.com`,
      password: "perf-pass",
      displayName: "Perf",
      workspaceSlug: slug,
    }),
  });
  const cookie = ridCookie(signup);

  const scenarios = buildScenarios({ baseUrl, cookie, workspaceId: randomUUID() });

  // Warm up the JIT + connection pool so the first scenario isn't penalized.
  for (const s of scenarios) {
    await Promise.all(Array.from({ length: 20 }, () => s.request()));
  }

  const results: PerfResult[] = [];
  for (const s of scenarios) {
    const res = await runLoad({ name: s.name, totalRequests: TOTAL, concurrency: CONCURRENCY }, s.request);
    results.push(res);
    process.stdout.write(
      `${s.name.padEnd(18)} ${fmt(res.rps, 0).padStart(7)} req/s  p50=${fmt(res.p50Ms, 2)}ms  p99=${fmt(res.p99Ms, 2)}ms  errors=${res.errors}\n`,
    );
  }

  const vcpus = os.cpus().length;
  const docUrl = new URL("../../../docs/capacity.md", import.meta.url);
  await writeFile(docUrl, capacityMarkdown(results, vcpus));
  process.stdout.write(`\nwrote ${docUrl.pathname}\n`);

  const evaluation = evaluateBudgets(results, HOT_PATH_BUDGETS);

  await app.close();
  await Promise.allSettled([closeDb(), closeRedis()]);

  if (!evaluation.ok) {
    process.stderr.write("\nPERF BUDGET VIOLATIONS:\n");
    for (const v of evaluation.violations) {
      process.stderr.write(`  ✗ ${v.name}: ${v.metric} ${fmt(v.actual, 2)} breached budget ${fmt(v.budget, 2)}\n`);
    }
    process.exit(1);
  }
  process.stdout.write("\n✓ all perf budgets met\n");
  process.exit(0);
}

main().catch((err) => {
  process.stderr.write(`perf suite failed: ${err instanceof Error ? err.stack : String(err)}\n`);
  process.exit(1);
});
